name: Memanggil Robot Bersama

on: workflow_dispatch

jobs:
  panggil-robot:
    uses: ashif-dev/belajar-actions/.github/workflows/robot-bersama.yml@v1
    with:
      nama-proyek: aplikasi-pembayaran
      jumlah-ulangan: 3
      pakai-huruf-besar: true
